twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
# configuration de bootstrap pour les formulaires de Symfony
when@test:
    twig:
        strict_variables: true
